### PR TITLE
address all buttons with classes instead of mix out of class+id

### PR DESCRIPTION
**Pull request by Kriechi**
address all buttons with classes instead of mix out of class+id

No behaviour or UI change - just a bit of code hygiene to have the same conventions across all buttons.

### CODE REVIEW

**Comment by makermelissa** [comment]
Have you verified the JS code still works? The reason it's mixed is because the ones that were classes were in 2 places (the mobile menu and the regular menu bar) and the JS code had to be updated for those to work properly.

**Review by makermelissa — CHANGES_REQUESTED** [review]
I'd like to verify that you tested all the changed menu items.

**Comment by Kriechi** [comment]
Yes, I did. There are four buttons that changed:
* the two mode buttons for Editor and Serial
* the Info button
* the Restart button on the Serial pane

I also grepped for all occurrences in the source code - pretty simple on 2 or 3 references for each.

**Review by makermelissa — APPROVED** [review]
Awesome. Thank you.

**Pull request merged**
