### PR TITLE
Update Web Bluetooth flag name

### PR DESCRIPTION
**Pull request by beaufortfrancois**
I've just added a flag to enable the Web Bluetooth API on Linux at `chrome://flags/#enable-web-bluetooth`

See https://twitter.com/quicksave2k/status/1489150418319990785

@makermelissa

### CODE REVIEW

**Comment by makermelissa** [comment]
Hi, on my system running Chrome 98.0.4758.80, this new option does not appear. My system is a bit older and this leads me to believe, that only the absolute newest systems would show this option. Perhaps you could reword it so that a user checks the new flag first and if they can't find it, they fall back to the existing flag for systems that may be a little older.

**Review by makermelissa — CHANGES_REQUESTED** [review]
Hi, on my system running Chrome 98.0.4758.80, this new option does not appear. My system is a bit older and this leads me to believe, that only the absolute newest systems would show this option. Perhaps you could reword it so that a user checks the new flag first and if they can't find it, they fall back to the existing flag for systems that may be a little older.

**Comment by beaufortfrancois** [comment]
@makermelissa I've edited prose. Let me know what you think.

**Review by makermelissa — APPROVED** [review]
Sounds good. Thanks.

**Pull request merged**
