### PR TITLE
Run CircuitPython code via REPL and get back result (attempt 2)

### PR DESCRIPTION
**Pull request by makermelissa**
This is just a duplicate of #46 so far. I want to test out web workflow and see what broke and will add on to this.

### CODE REVIEW

**Comment by makermelissa** [comment]
Ok, making progress on this. The code that interacts with the REPL has been refactored into a separate file now. I'm still tracing down the bug that's causing Web Workflow to not run.

**Comment by makermelissa** [comment]
Ok, finally fixed the bug. I just want to do some additional testing before changing it to a regular PR. I may also publish the REPL component in its own repo first.

**Comment by makermelissa** [comment]
I may throw a quick fix in for #47 as well.

**Comment by makermelissa** [comment]
Found and fixed a couple more bugs. It looks like this fixes #47 without needing to add any additional code.

**Comment by tannewt** [comment]
Let me know when its ready for review! Thanks for the fixes.

**Comment by makermelissa** [comment]
It's super close. I'm just cleaning up the flow a bit. Right now it attempts to load the FileSystemAccess API handle when you click the button and doesn't give you a chance to select a different folder unless it can't connect, which could be problematic. After that's solved, it should be ready.

**Comment by makermelissa** [comment]
Ok, it seems to be working well now.

**Comment by makermelissa** [comment]
A lot of functionality was moved to https://github.com/adafruit/circuitpython-repl-js so it could be used by the CircuitPython Installer.

**Review by tannewt — APPROVED** [review]
Looks good to me! I'll let you merge when you are ready.

**Comment by makermelissa** [comment]
Sounds good. It should be good to go.

**Pull request merged**
